Fix Nexmo::Signature for compatibility with ruby-jwt v2
Currently raising NoMethodError: undefined method `secure_compare' because
the secure_compare method has been moved into a JWT::SecurityUtils module.